### ISSUE TITLE
If a user's Git credentials are not set then it throws an error.

### ISSUE THREAD

**Issue by earlalex** [micalexander/obi#1]
.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command': git '--git-dir=/www/wordpress/.git' '--work-tree=/www/wordpress' commit '--message=initial commit' '--all'  2>&1: (Git::GitExecuteError)
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

 -author:earlalex

**Comment by wizalexander** [comment]
This issue is now fixed
